<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\API\AuthController;
use App\Http\Controllers\API\RegisterController;
use App\Http\Controllers\API\ProfileController;
use App\Http\Controllers\API\CMSController;
use App\Http\Controllers\API\BlogController;
use App\Http\Controllers\API\DataController;
use App\Http\Controllers\API\FolderController;
use App\Http\Controllers\API\FileController;
use App\Http\Controllers\API\HomeController;
use App\Http\Controllers\API\DocsController;
use App\Http\Controllers\API\ReminderController;
use App\Http\Controllers\API\MeasurementController;
use App\Http\Controllers\API\MedicoSearchController;
use App\Http\Controllers\API\SearchController;
use App\Http\Controllers\API\BookmarkController;
use App\Http\Controllers\API\ShareController;
use App\Http\Controllers\API\DeleteAccountController;
use App\Http\Controllers\API\ReminderCronController;
use App\Http\Controllers\API\DeviceVitalController;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
*/

Route::prefix('v1')->group(function () {
    // Public routes.
    Route::post('login', [AuthController::class, 'login']);
    Route::post('verify/otp', [AuthController::class, 'verify']);

    // MQTT Gateway webhook (public - receives data from MQTT broker/ThingsBoard)
    Route::post('gateway/telemetry', [DeviceVitalController::class, 'mqttWebhook']);

    Route::get('cms/about', [CMSController::class, 'about']);
    Route::get('cms/contact-us', [CMSController::class, 'contact_us']);
    Route::get('cms/privacy-policy', [CMSController::class, 'privacy_policy']);
    Route::get('cms/terms-and-conditions', [CMSController::class, 'terms_and_conditions']);

    Route::get('blogs', [BlogController::class, 'blogs']);
    Route::get('blog/view/{id}', [BlogController::class, 'blog_view']);
    Route::get('banners', [DataController::class, 'banners']);

    // Links generated by backend emails/shares.
    Route::get('email-verify', [RegisterController::class, 'verify_email']);
    Route::get('share/assets', [ShareController::class, 'assets_public_access']);

    // Requires auth token but no selected profile.
    Route::middleware('token.validate')->group(function () {
        Route::post('register', [RegisterController::class, 'register']);
        Route::post('profile-login', [AuthController::class, 'profile_login']);
        Route::get('profiles', [ProfileController::class, 'profiles']);
        Route::post('profile/create', [ProfileController::class, 'create_profile']);
        Route::post('logout', [AuthController::class, 'logout']);
        Route::post('logout-all-device', [AuthController::class, 'logoutFromAllDevice']);

        Route::post('email-verification-request', [RegisterController::class, 'email_verification_request']);
    });

    // Requires selected profile context.
    Route::middleware('profile.validate')->group(function () {
        // Profile.
        Route::get('profile/get', [ProfileController::class, 'my_profile']);
        Route::post('profile/update', [ProfileController::class, 'update_profile']);
        Route::post('profile/update/icon', [ProfileController::class, 'update_profile_icon']);
        Route::post('profile/update/current-location', [ProfileController::class, 'update_current_location']);
        Route::get('email/is-verified', [RegisterController::class, 'email__is_verified']);
        Route::post('delete-account', [DeleteAccountController::class, 'delete']);

        // Home/dashboard data.
        Route::get('notifications', [DataController::class, 'notifications']);
        Route::get('recent-uploads', [HomeController::class, 'recent_uploads']);
        Route::get('categories', [DataController::class, 'categories']);
        Route::get('suggetions', [DataController::class, 'suggetions']);

        // Search and medico.
        Route::get('search', [SearchController::class, 'search']);
        Route::get('filters', [SearchController::class, 'filters']);
        Route::get('files-and-folders', [SearchController::class, 'files_and_folders']);
        Route::get('folders-and-files', [DataController::class, 'folders_and_files']);
        Route::get('medico-search', [MedicoSearchController::class, 'search']);
        Route::get('medico-featured', [MedicoSearchController::class, 'featured']);
        Route::get('medico-search-details', [MedicoSearchController::class, 'search_details']);

        // Blogs.
        Route::get('blogs/categories', [BlogController::class, 'categories']);

        // My docs.
        Route::get('my-documents', [DocsController::class, 'my']);

        // Folders/files.
        Route::post('folder/create', [FolderController::class, 'store']);
        Route::get('folder/get', [FolderController::class, 'get']);
        Route::post('folder/rename', [FolderController::class, 'rename']);
        Route::post('folder/move', [FolderController::class, 'move']);
        Route::get('folder/delete/{folder_id}', [FolderController::class, 'delete']);

        Route::post('file/uploader', [FileController::class, 'file_uploader']);
        Route::post('file', [FileController::class, 'store']);
        Route::get('file/get', [FileController::class, 'get']);
        Route::get('file/{file_id}/download', [FileController::class, 'download']);
        Route::post('file/rename', [FileController::class, 'rename']);
        Route::post('file/move', [FileController::class, 'move']);
        Route::post('file/copy', [FileController::class, 'copy']);
        Route::get('file/delete/{file_id}', [FileController::class, 'delete']);

        // Reminder.
        Route::post('reminders', [ReminderController::class, 'store']);
        Route::get('reminders', [ReminderController::class, 'get']);
        Route::post('reminders/update', [ReminderController::class, 'update']);
        Route::post('reminders/status', [ReminderController::class, 'status']);
        Route::get('reminders/delete/{id}', [ReminderController::class, 'delete']);
        Route::get('reminders/view/{id}', [ReminderController::class, 'view']);
        Route::post('reminders/taken/{id}', [ReminderController::class, 'taken']);
        Route::post('reminders/snooze/{id}', [ReminderController::class, 'snooze']);
        Route::get('reminders/suggetions', [ReminderController::class, 'suggetions']);

        // Measurements.
        Route::post('measurements', [MeasurementController::class, 'store']);
        Route::get('measurements', [MeasurementController::class, 'get']);
        Route::get('measurements/delete/{id}', [MeasurementController::class, 'delete']);
        Route::get('measurements/analytics', [MeasurementController::class, 'analytics']);

        // Device Vitals (from BLE hardware via MQTT).
        Route::post('device-vitals', [DeviceVitalController::class, 'store']);
        Route::get('device-vitals', [DeviceVitalController::class, 'get']);
        Route::get('device-vitals/latest', [DeviceVitalController::class, 'latest']);
        Route::get('device-vitals/analytics', [DeviceVitalController::class, 'analytics']);
        Route::get('device-vitals/devices', [DeviceVitalController::class, 'devices']);
        Route::post('device-vitals/link-device', [DeviceVitalController::class, 'linkDevice']);
        Route::get('device-vitals/delete/{id}', [DeviceVitalController::class, 'delete']);

        // Bookmark.
        Route::get('bookmark/get', [BookmarkController::class, 'get']);
        Route::get('bookmark/add', [BookmarkController::class, 'store']);
        Route::get('bookmark/remove', [BookmarkController::class, 'remove']);

        // Sharing.
        Route::post('share', [ShareController::class, 'share']);
        Route::post('share-to-family', [ShareController::class, 'share_to_family']);
        Route::get('get/shared', [ShareController::class, 'get_shared']);
        Route::get('get/my-shared', [ShareController::class, 'get_my_shared']);
        Route::get('shared/remove/{shared_id}', [ShareController::class, 'shared_remove']);
        Route::post('my-shared/remove/{shared_id}', [ShareController::class, 'my_shared_remove']);
        Route::get('my-shared/profiles/{id}', [ShareController::class, 'get_my_shared_profiles']);
        Route::get('members/check-phone/{phone}', [ShareController::class, 'check_is_phone_our_member']);
        Route::get('share/direct', [ShareController::class, 'direct_share']);

        // Optional manual trigger.
        Route::get('reminder-cron', [ReminderCronController::class, 'reminders']);
    });
});

// Default Laravel example route (kept for compatibility).
Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});
